n transformations: 15
transformations:
  - remove comments:
      p: 1.0
  - rename entities:
      p: 0.5
      seed: 9
      max tokens: 2
      max token len: 3
      rename functions: true
      rename variables: true
      test: true
  - for to while:
      p: 1.0
  - if else swap:
      p: 1.0
  - printf to cout:
      p: 1.0
  - while to for:
      p: 1.0
  - reorder function decls:
      p: 1.0
      seed: 9
      test: true