name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:


    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
          sudo apt update
          sudo apt install llvm-9-dev libclang-9-dev
      - name: Lint
        run: |
          echo "Linting is not implemented yet"
      - name: Build
        run: |
          mkdir cmake-build-debug && cd cmake-build-debug
          cmake -DCMAKE_PREFIX_PATH="/usr/lib/llvm-9/cmake;/usr/lib/llvm-9/lib/cmake/clang" -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build .
