name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          sh scripts/install_requirements.sh
      - name: Lint
        run: |
          cpplint --filter=-legal,-build main.cpp
      - name: Build
        run: |
          mkdir cmake-build-debug && cd cmake-build-debug
          cmake -DLLVM_DIR=build/clang+llvm-9/lib/cmake/llvm -DClang_DIR=build/clang+llvm-9/lib/cmake/clang ..
          cmake --build .
      - name: Test
        run: |
          echo "Tests are not implemented yet"
