name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Show env variables
        run: |
          echo "::group::My title"
          echo "Hello"
          echo "${ACTUAL_DATA}"
          echo "${ANTI_PLAGIARISM_DATA}"
          echo "${GITHUB_WORKSPACE}"
          echo "::endgroup::"
      - name: Install python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install clang
        run: |
          sudo apt update
          sudo apt install libomp5 libomp-dev
          sh scripts/install_clang.sh
      - name: Lint
        run: |
          cpplint --filter=-legal --recursive --exclude=build --exclude=tests/resources --linelength=120 .
      - name: Build
        run: |
          cd build
          cmake -DLLVM_DIR=build/clang+llvm-9/lib/cmake/llvm \
                -DClang_DIR=build/clang+llvm-9/lib/cmake/clang \
                -DCMAKE_C_COMPILER="${GITHUB_WORKSPACE}/build/clang+llvm-9/bin/clang" \
                -DCMAKE_CXX_COMPILER="${GITHUB_WORKSPACE}/build/clang+llvm-9/bin/clang++" ..
          cmake --build .
      - name: Test
        run: |
          pytest
