name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sh scripts/install_requirements.sh
      - name: Lint
        run: |
          echo "Linting is not implemented yet"
      - name: Build
        run: |
          mkdir cmake-build-debug && cd cmake-build-debug
          cmake -DLLVM_DIR=build/clang+llvm-9/lib/cmake/llvm -DClang_DIR=build/clang+llvm-9/lib/cmake/clang ..
          cmake --build .
      - name: Test
        run: |
          echo "Tests are not implemented yet"
